version: "3.9"

services:
  backend:
    build: ./backend
    container_name: courtierpro_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    build: ./frontend
    container_name: courtierpro_frontend
    ports:
      - "8081:80"

