server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/courtierpro
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          #  tenant Auth0
          issuer-uri: https://${AUTH0_DOMAIN}/

          audiences:
            - ${AUTH0_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
  ses:
    region: ${AWS_REGION}

auth0:
  domain: ${AUTH0_DOMAIN}
  audience: ${AUTH0_AUDIENCE}
  management:
    client-id: ${AUTH0_MGMT_CLIENT_ID}
    client-secret: ${AUTH0_MGMT_CLIENT_SECRET}
    audience: ${AUTH0_MGMT_AUDIENCE}
