server:
  port: 8080

app:
  frontendBaseUrl: ${FRONTEND_URL}
  email:
    provider: ses
    from-address: ${EMAIL_FROM_ADDRESS:support@courtier-pro.ca}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/courtierpro
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate   # Flyway manages schema, Hibernate only validates

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          # Auth0 tenant
          issuer-uri: https://${AUTH0_DOMAIN}/
          audiences:
            - ${AUTH0_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET}
    endpoint: ${AWS_S3_ENDPOINT}
    access-key: ${R2_ACCESS_KEY_ID}
    secret-key: ${R2_SECRET_ACCESS_KEY}
  ses:
    region: ${AWS_SES_REGION:us-east-1}
    access-key: ${AWS_SES_ACCESS_KEY_ID}
    secret-key: ${AWS_SES_SECRET_ACCESS_KEY}

auth0:
  domain: ${AUTH0_DOMAIN}
  audience: ${AUTH0_AUDIENCE}
  management:
    client-id: ${AUTH0_MGMT_CLIENT_ID}
    client-secret: ${AUTH0_MGMT_CLIENT_SECRET}
    audience: ${AUTH0_MGMT_AUDIENCE}

gmail:
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_PASSWORD}
